version: '3.4'

services:
  proxy:
    image: linuxserver/swag
    container_name: underbudget-proxy
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    env_file: .proxy.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy:/config

  authelia:
    image: authelia/authelia
    container_name: underbudget-auth
    restart: unless-stopped
    env_file: .auth.env
    volumes:
      - ./authelia:/config

  db:
    image: postgres
    container_name: underbudget-db
    restart: unless-stopped
    env_file: .db.env
    volumes:
      - db-data:/var/lib/postgresql/data

  db-backup:
    image: prodrigestivill/postgres-backup-local
    container_name: underbudget-backup
    restart: always
    volumes:
      - ./backups:/backups
    links:
      - db
    depends_on:
      - db
    env_file:
      - .db.env
      - .backup.env

  api:
    build: backend
    container_name: underbudget-api
    restart: always
    depends_on:
      - db
    env_file: .db.env

  app:
    build: webapp
    container_name: underbudget-app
    restart: always
    depends_on:
      - api

volumes:
  db-data:
    name: underbudget-db-data
