"""Add reconciliation table

Revision ID: f9c4ce3bedd8
Revises: 4b585a442fb5
Create Date: 2021-09-04 12:36:57.211693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c4ce3bedd8'
down_revision = '4b585a442fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('beginning_balance', sa.Integer(), nullable=False),
    sa.Column('beginning_date', sa.Date(), nullable=False),
    sa.Column('ending_balance', sa.Integer(), nullable=False),
    sa.Column('ending_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account_transaction', sa.Column('reconciliation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account_transaction', 'reconciliation', ['reconciliation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account_transaction', type_='foreignkey')
    op.drop_column('account_transaction', 'reconciliation_id')
    op.drop_table('reconciliation')
    # ### end Alembic commands ###
