name: Continuous Integration
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/dev-requirements.txt
    - name: Lint
      run: make -C backend/ style
    - name: Build dev container
      run: make dev-build
    - name: Start dev containers
      run: |
        make dev-up
        make dev-ps
    - name: Wait for dev containers
      uses: mydea/action-wait-for-api@v1
      with:
        url: "http://localhost:5000/health"
    - name: Run API tests
      run: |
        make dev-db-upgrade
        make api-test
    - name: Upload API coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: backend
        fail_ci_if_error: true

  build-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
    - uses: actions/checkout@v2
    - name: Cache NPM packages
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Set up Node 13.x
      uses: actions/setup-node@v2
      with:
        node-version: '13.x'
    - run: npm ci
    - run: npm run build
    - run: npm run test:coverage
    - run: npm run lint
    - name: Upload webapp coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./webapp/coverage/clover.xml
        flags: webapp
        fail_ci_if_error: true
